services:
  grocery:
    image: grocery-price-fetcher:latest
    ports:
      - 80:3000
    volumes:
      - type: bind
        source: /var/lib/grocery-price-fetcher/
        target: /mnt/grocery-price-fetcher/

