services:
  grocery:
    image: grocery-price-fetcher
    ports:
      - 80:3000
    volumes:
      - data:/mnt/grocery-price-fetcher/
      - /etc/grocery-price-fetcher/config.yaml:/etc/grocery-price-fetcher/config.yaml:ro
    links:
      - prepopulate
    depends_on:
      prepopulate:
        condition: service_completed_successfully
  prepopulate:
    image: ubuntu
    command: ["/mnt/sample-data/prepopulate.sh", "/mnt/sample-data/data", "/mnt/grocery-price-fetcher"]
    volumes:
      - data:/mnt/grocery-price-fetcher/
      - ./sample-data:/mnt/sample-data/:ro
volumes:
  data:
    driver: local
