# This is the configuration file for the grocery-price-fetcher service.
# All paths and ports are as seen from inside the container.
verbosity: 1
daemon:
  host: '0.0.0.0'
  certfile: /run/secrets/cert
  keyfile: /run/secrets/key
services:
  database:
    type: mysql
    options:
      user: root
      passwordfile: /run/secrets/db_root_password
      host: database
      port: '3306'
  pricing:
    refreshrate: 6h0m0s

