# This is the configuration file for the grocery-price-fetcher service.
# All paths and ports are as seen from inside the container.
verbosity: 1
frontend: /usr/share/grocery-price-fetcher/frontend
address: '[::]:3000'
services:
    database:
        type: mysql
        options:
            user:     root
            password: example
            host:     database
            port:     '3306'
    helloworld:
        enable: true
    menu:
        enable: true
    pantry:
        enable: true
    pricing:
        enable: true
        refreshrate: 6h0m0s
    recipes:
        enable: true
    version:
        enable: true

