# This is the configuration file for the grocery-price-fetcher service.
# All paths and ports are as seen from inside the container.
verbosity: 1
frontend: /usr/share/grocery-price-fetcher/frontend
address: '[::]:3000'
services:
    database:
        type: json
        options:
            menus: /mnt/grocery-price-fetcher/menus.json
            pantries: /mnt/grocery-price-fetcher/pantries.json
            products: /mnt/grocery-price-fetcher/products.json
            recipes: /mnt/grocery-price-fetcher/recipes.json
    helloworld:
        enable: true
    menu:
        enable: true
    pantry:
        enable: true
    pricing:
        enable: true
        refreshrate: 6h0m0s
    recipes:
        enable: true
    version:
        enable: true

