# This is the configuration file for the grocery-price-fetcher service.
# All paths and ports are as seen from inside the container.
verbosity: 1
frontend: /usr/share/grocery-price-fetcher/frontend
address: '[::]:3000'
services:
  database:
    type: mysql
    options:
      user: root
      passwordfile: /run/secrets/db_root_password
      host: database
      port: '3306'
  pricing:
    enable: true
    refreshrate: 6h0m0s

