# This is the configuration file for the grocery-price-fetcher service.
# All paths and ports are as seen from inside the container.
verbosity: 1
daemon:
  host: '0.0.0.0'
  certfile: /run/secrets/cert
  keyfile: /run/secrets/key
services:
  database:
    type: mysql
    options:
      user: root
      password-file: /run/secrets/db_root_password
      host: database
      port: '3306'
  auth:
    google:
      client-id: 1097497200114-7sf1777fi3jm2vob9ihp8gmnjrj84g8s.apps.googleusercontent.com
      client-secret-file: /run/secrets/google_client_secret
      redirect-uri: https://localhost
  pricing:
    refreshrate: 6h0m0s

