name: Deploy

on:
  workflow_dispatch:
  push: 
    tags:
      - 'v*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Authenticate to Google Cloud
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: ${{ secrets.GCLOUD_JSON_CREDENTIALS }}
    - name: Authenticate to Docker
      run: |
        sudo docker login                                   \
            --username '${{ secrets.DOCKER_USER }}'         \
            --password '${{ secrets.DOCKER_PASSWORD }}'
    - name: 'Set up Google Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v2'
      with:
        version: '>= 476.0.0'
    - name: Install Make
      run: |
          export DEBIAN_NONINTERACTIVE=1
          sudo apt update
          sudo apt install -y make
    - name: Install Docker
      run: |
        export DEBIAN_NONINTERACTIVE=1
        sudo apt install -y ca-certificates curl gnupg lsb-release
        sudo mkdir -p /etc/apt/keyrings
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
        echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
        sudo apt update
        sudo apt install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
    - name: Set up node
      uses: actions/setup-node@v4
      with:
          node-version: '18'
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
          go-version-file: go.work
          check-latest: true
          cache: false
    - name: Build container
      run: make build-docker
    - name: Write SSH keys
      run: |
        mkdir -p ~/.ssh

        install -m 0600 -D /dev/null ~/.ssh/id_ed25519
        cat << EOF > ~/.ssh/id_ed25519
        ${{ secrets.SSH_PRIVATE_KEY }}
        EOF

        cat << EOF > ~/.ssh/config
        Host azurevm
          HostName ${{ secrets.SSH_TARGET }}
          User edu
          Port 22
          IdentityFile ~/.ssh/id_ed25519
        EOF

        ssh-keyscan -H ${{ secrets.SSH_TARGET }} | tee ~/.ssh/known_hosts
    - name: Deploy
      run: |
        eval $(ssh-agent -s)
        ssh-add ~/.ssh/id_ed25519
        make deploy                                   \
            DOCKER_USER="${{ secrets.DOCKER_USER }}"  \
            SSH_TARGET='azurevm'                      \
            FQDN='https://lacompradeledu.cat'
    - name: Upload package
      uses: actions/upload-artifact@v4
      with:
        name: grocery-price-fetcher.tar.gz
        path: ${{ github.workspace }}/deploy/host/grocery-price-fetcher.tar.gz