name: Quality

on:
  pull_request:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  quality-go:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        module: [backend, end-to-end]
    steps:
    - name: Check out repository
      uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version-file: go.work
        check-latest: true
        cache: false
    - name: Install Make
      run: |
        export DEBIAN_NONINTERACTIVE=1
        sudo apt update
        sudo apt install -y make
    - name: Tidy up
      working-directory: ${{ github.workspace }}/${{ matrix.module}}
      run: |
        go mod tidy
        if [ -n "$(git status --porcelain)" ]; then
          echo "Error: go.mod and/or go.sum are out of sync. Please run 'go mod tidy' and commit the changes." 1>&2
          exit 1
        fi
    - name: Build
      if: matrix.module != 'end-to-end'
      working-directory: ${{ github.workspace }}/${{ matrix.module}}
      run: make build
    - name: Lint
      uses: golangci/golangci-lint-action@v6
      with:
        version: latest
        working-directory: ${{ github.workspace }}/${{ matrix.module}}

  test-go:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v4
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version-file: go.work
        check-latest: true
        cache: false
    - name: Install Make
      run: |
        export DEBIAN_NONINTERACTIVE=1
        sudo apt update
        sudo apt install -y make
    - name: Run tests
      run: make test-go

  quality-js:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v4
    - name: Install Make
      run: |
        export DEBIAN_NONINTERACTIVE=1
        sudo apt update
        sudo apt install -y make
    - name: Set up node
      uses: actions/setup-node@v4
      with:
        node-version: '18'
    - name: Build front-end
      run: make build-js
  
  end-to-end:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v4
    - name: Install Make
      run: |
        export DEBIAN_NONINTERACTIVE=1
        sudo apt update
        sudo apt install -y make npm curl
    - name: Set up node
      uses: actions/setup-node@v4
      with:
        node-version: '18'
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version-file: go.work
        check-latest: true
        cache: false
    - name: Run end-to-end tests
      run: make test-e2e